# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-19 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20191219_0905'),
        ('app01', '0007_auto_20191212_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name_plural': '课程记录表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name_plural': '学习记录表'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role'),
        ),
    ]
